# Generated by Django 5.0.6 on 2026-08-30 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sequence_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('INVALIDATED', 'Invalidated')], default='ACCEPTED', max_length=12)),
                ('invalidated_reason', models.TextField(blank=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='auctions.auction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='accounts.bidderprofile')),
                ('invalidated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence_no'],
                'indexes': [models.Index(fields=['auction', 'status'], name='bidding_bid_auction_d9cf82_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('auction', 'sequence_no'), name='unique_sequence_per_auction'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='bid_amount_positive'),
        ),
    ]
