# Generated by Django 5.0.6 on 2026-08-30 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_REGISTERED', 'User registered'), ('USER_VERIFIED', 'User verified'), ('USER_SUSPENDED', 'User suspended'), ('AUCTION_CREATED', 'Auction created'), ('AUCTION_APPROVED', 'Auction approved'), ('AUCTION_REJECTED', 'Auction rejected'), ('AUCTION_STARTED', 'Auction started'), ('BID_PLACED', 'Bid placed'), ('BID_REJECTED', 'Bid rejected'), ('BID_INVALIDATED', 'Bid invalidated'), ('AUCTION_EXTENDED', 'Auction extended'), ('AUCTION_CLOSED', 'Auction closed'), ('WINNER_DETERMINED', 'Winner determined'), ('AUCTION_CANCELLED', 'Auction cancelled'), ('DISPUTE_CREATED', 'Dispute created'), ('DISPUTE_RESOLVED', 'Dispute resolved'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_RECEIVED', 'Payment received'), ('PAYMENT_FAILED', 'Payment failed'), ('PAYMENT_REFUNDED', 'Payment refunded')], max_length=32)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx')],
            },
        ),
    ]
