# Generated by Django 5.0.6 on 2026-08-30 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('OUTBID', "You've been outbid"), ('AUCTION_WON', 'You won an auction'), ('AUCTION_LIVE', 'Your auction is now live'), ('AUCTION_CLOSED_NO_WINNER', 'Auction closed with no winner'), ('LISTING_APPROVED', 'Listing approved'), ('LISTING_REJECTED', 'Listing rejected'), ('ACCOUNT_VERIFIED', 'Account verified'), ('ACCOUNT_REJECTED', 'Account verification rejected'), ('ACCOUNT_SUSPENDED', 'Account suspended'), ('ACCOUNT_REACTIVATED', 'Account reactivated'), ('PAYMENT_RECEIVED', 'Payment received'), ('PAYMENT_FAILED', 'Payment marked failed')], max_length=32)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('SMS', 'SMS')], default='IN_APP', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=64)),
                ('related_object_id', models.CharField(blank=True, max_length=64)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='notificatio_related_f82ec2_idx')],
            },
        ),
    ]
